### ISSUE TITLE
KeyError: 'road_plane'

### ISSUE THREAD

**Issue by VividLe** [yifanzhang713/IA-SSD#4]
Thanks for your fantastic work. Following your instruction, I can obtain similar inference results with you. However, the training process with command "python train.py --cfg_file cfgs/kitti_models/IA-SSD.yaml" encounters the following errors. Any advices about how to fix it?

2022-03-30 15:08:13,569   INFO  **********************Start training kitti_models/IA-SSD(default)**********************
epochs:   0%|                                                                                                                                                                          | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                    | 0/464 [00:00<?, ?it/s]
  File "train.py", line 205, in <module>
    main()
  File "train.py", line 174, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/disk/yangle/IA-SSD/tools/train_utils/train_utils.py", line 118, in train_model
    dataloader_iter=dataloader_iter
  File "/disk/yangle/IA-SSD/tools/train_utils/train_utils.py", line 25, in train_one_epoch
    batch = next(dataloader_iter)
  File "/disk/yangle/software/anaconda3/envs/iassd/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/disk/yangle/software/anaconda3/envs/iassd/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/disk/yangle/software/anaconda3/envs/iassd/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/disk/yangle/software/anaconda3/envs/iassd/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/disk/yangle/software/anaconda3/envs/iassd/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk/yangle/software/anaconda3/envs/iassd/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../pcdet/datasets/kitti/kitti_dataset.py", line 424, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "../pcdet/datasets/dataset.py", line 130, in prepare_data
    'gt_boxes_mask': gt_boxes_mask
  File "../pcdet/datasets/augmentor/data_augmentor.py", line 281, in forward
    data_dict = cur_augmentor(data_dict=data_dict)
  File "../pcdet/datasets/augmentor/database_sampler.py", line 245, in __call__
    data_dict = self.add_sampled_boxes_to_scene(data_dict, sampled_gt_boxes, total_valid_sampled_dict)
  File "../pcdet/datasets/augmentor/database_sampler.py", line 163, in add_sampled_boxes_to_scene
    sampled_gt_boxes, data_dict['road_plane'], data_dict['calib']
KeyError: 'road_plane'

**Comment by VividLe** [comment]
Solved by following this [advice](https://github.com/sshaoshuai/PointRCNN/issues/12#issuecomment-484769943).

**Comment by yifanzhang713** [comment]
Hi @VividLe,
Thanks for your interest! Yeah you should download the **road plane** file to support the augmentaion. Reminded by your question,  we have re-added the relevant instructions in the **README.md**.

Best wishes!
