### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by huangmang** [yifanzhang713/IA-SSD#40]
作者你好，我在训练IASSD时到68%，使用给的权重也在测试到68%报错，报错如下希望楼主解答非常感谢。
Traceback (most recent call last):
  File "test.py", line 203, in <module>
    main()
  File "test.py", line 199, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "test.py", line 65, in eval_single_ckpt
    eval_utils.eval_one_epoch(
  File "/data3/huangmang2/IA-SSD/tools/eval_utils/eval_utils.py", line 54, in eval_one_epoch
    for i, batch_dict in enumerate(dataloader):
  File "/data2/huangmang/anaconda3/envs/IASSD/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/data2/huangmang/anaconda3/envs/IASSD/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/data2/huangmang/anaconda3/envs/IASSD/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/data2/huangmang/anaconda3/envs/IASSD/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/data2/huangmang/anaconda3/envs/IASSD/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/data2/huangmang/anaconda3/envs/IASSD/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data2/huangmang/anaconda3/envs/IASSD/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data3/huangmang2/IA-SSD/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 408, in __getitem__
    points = self.get_lidar(sample_idx)
  File "/data3/huangmang2/IA-SSD/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 65, in get_lidar
    assert lidar_file.exists()
AssertionError

**Comment by yifanzhang713** [comment]
Hi, thanks for your following. I guess there may be a problem with your dataset deployment, please download and unzip it again.

**Comment by huangmang** [comment]
Thank you yifan,I have solved this problem,I found the lidar data is incomplete.
