### ISSUE TITLE
Distributed Training 

### ISSUE THREAD

**Issue by YoushaaMurhij** [yifanzhang713/IA-SSD#7]
I tried to train this model on Waymo dataset with the defaut configs but I am facing this error:
```bash
epochs:   0%|          | 0/30 [00:00<?, ?it/s]
epochs:   0%|          | 0/30 [00:00<?, ?it/s]
epochs:   0%|          | 0/30 [00:00<?, ?it/s]
epochs:   0%|          | 0/30 [00:00<?, ?it/s]
epochs:   0%|          | 0/30 [00:00<?, ?it/s]
epochs:   0%|          | 0/30 [00:00<?, ?it/s]Exception ignored in: <function DataBaseSampler.__del__ at 0x7f6d406b9560>
Traceback (most recent call last):
  File "../pcdet/datasets/augmentor/database_sampler.py", line 60, in __del__
    if self.use_shared_memory:
AttributeError: 'DataBaseSampler' object has no attribute 'use_shared_memory'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/AI/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/AI/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)

```
Here's  `dist_train.sh ` :
```bash
#!/usr/bin/env bash
set -x
NGPUS=$1
PY_ARGS=${@:2}

while true
do
    PORT=$(( ((RANDOM<<15)|RANDOM) % 49152 + 10000 ))
    status="$(nc -z 127.0.0.1 $PORT < /dev/null &>/dev/null; echo $?)"
    if [ "${status}" != "0" ]; then
        break;
    fi
done
echo $PORT

python -m torch.distributed.launch --nproc_per_node=${NGPUS} --master_port $PORT train.py --launcher pytorch ${PY_ARGS}
```

Any suggestions? 
Thanks

**Comment by YoushaaMurhij** [comment]
I can see that '`use_shared_memory`' is already added [HERE](https://github.com/yifanzhang713/IA-SSD/blob/88d6bd18e2733ef24589d00492eefafadd60a704/pcdet/datasets/augmentor/database_sampler.py#L23).

**Comment by YoushaaMurhij** [comment]
Launch command: `bash ./scripts/dist_train.sh 6 --cfg_file ./cfgs/waymo_models/IA-SSD.yaml;`

**Comment by YoushaaMurhij** [comment]
Solved by reducing number of workers per device.
